/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum NpmAgent {
  yarn = 'yarn',
  pnpm = 'pnpm',
  npm = 'npm'
}
export interface NpmAgentConfig {
  agent: NpmAgent
  version: string
}
export function getNpmAgent(npmConfigUserAgent: string): NpmAgentConfig
export function sum(a: number, b: number): number
